version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: reachinbox_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scheduler
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: reachinbox_redis
    ports:
      - "6379:6379"
